#!/usr/bin/env python3

import os
from dotenv import load_dotenv

load_dotenv()

print("=== Quick Supabase Fix Guide ===")
print()
print("The current project domain is not resolving. Here's how to fix it:")
print()
print("1. GO TO SUPABASE DASHBOARD:")
print("   https://supabase.com/dashboard")
print()
print("2. CREATE NEW PROJECT:")
print("   - Click 'New Project'")
print("   - Name: 'TeenBuzz-Fixed'")
print("   - Choose a strong password")
print("   - Select region: US East (fastest)")
print("   - Click 'Create new project'")
print()
print("3. WAIT 2-3 MINUTES for setup")
print()
print("4. GET NEW CREDENTIALS:")
print("   - Go to Settings → API")
print("   - Copy the new Project URL")
print("   - Copy the new anon public key")
print()
print("5. UPDATE YOUR .env FILE:")
print("   Replace these lines in your .env file:")
print(f"   OLD URL: {os.getenv('SUPABASE_URL')}")
print("   NEW URL: https://[new-project-id].supabase.co")
print()
print("6. TEST CONNECTION:")
print("   Run: python test_database_fix.py")
print()
print("This should work immediately with a new project!")
print()
print("Alternative: Try these DNS fixes first...")
print()
print("DNS FIX 1 - Change DNS Server:")
print("   System Preferences → Network → Advanced → DNS")
print("   Add: 8.8.8.8 and 8.8.4.4")
print("   Click OK and restart your browser")
print()
print("DNS FIX 2 - Flush DNS Cache:")
print("   Run: sudo dscacheutil -flushcache")
print("   Then: sudo killall -HUP mDNSResponder")
print()
print("DNS FIX 3 - Try Different Network:")
print("   - Use mobile hotspot")
print("   - Try different WiFi network")
print("   - Use VPN if available")
